// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTk0hd2I8VvP6gJZAySdUvsCfShPwXSQ',
    appId: '1:512647254623:web:021a506677c94e41c401ea',
    messagingSenderId: '512647254623',
    projectId: 'grasscuttingrobot',
    authDomain: 'grasscuttingrobot.firebaseapp.com',
    storageBucket: 'grasscuttingrobot.appspot.com',
    measurementId: 'G-ZXK4755XJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrduzn6iXRxrjg9Vgs51p2pYUkkcrAF4',
    appId: '1:512647254623:android:30c86856e47fd4cfc401ea',
    messagingSenderId: '512647254623',
    projectId: 'grasscuttingrobot',
    storageBucket: 'grasscuttingrobot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSws5B5e0RxNm-SX_KgnKI6W6xBlLf8Zo',
    appId: '1:512647254623:ios:541b9b4071e61b3ec401ea',
    messagingSenderId: '512647254623',
    projectId: 'grasscuttingrobot',
    storageBucket: 'grasscuttingrobot.appspot.com',
    iosBundleId: 'com.example.grassCuttingRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSws5B5e0RxNm-SX_KgnKI6W6xBlLf8Zo',
    appId: '1:512647254623:ios:541b9b4071e61b3ec401ea',
    messagingSenderId: '512647254623',
    projectId: 'grasscuttingrobot',
    storageBucket: 'grasscuttingrobot.appspot.com',
    iosBundleId: 'com.example.grassCuttingRobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTk0hd2I8VvP6gJZAySdUvsCfShPwXSQ',
    appId: '1:512647254623:web:712b8c65cdc21729c401ea',
    messagingSenderId: '512647254623',
    projectId: 'grasscuttingrobot',
    authDomain: 'grasscuttingrobot.firebaseapp.com',
    storageBucket: 'grasscuttingrobot.appspot.com',
    measurementId: 'G-ZZ2RS2B63X',
  );
}
